apiVersion: v1
kind: Service
metadata:
  name: jobson
  labels:
    component: jobson
spec:
  selector:
    component: jobson
  ports:
  - port: 8080
    name: http
    protocol: TCP
  - port: 8081
    name: admin
    protocol: TCP
